# folder settings
source: .
destination: ./_site

# site settings
permalink: /:categories/:title
markdown: redcarpet

# markdown engine
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "lax_spacing", "strikethrough", "superscript"]

# custom vars, most of them are used by index.xml
url:
title: 我要去呼伦贝尔!
description: 呼伦贝尔草原深度攻略
name: matthew
full-name: Xiang Zhuyuan
email: xiangzhuyuan@gmail.com
slogan: walk by my faith!
twitter: xiangzhuyuan

# fire up a localhost and auto generate when files change
serve: ture
port: 4321

# exclude files for generated site
exclude:
- README.md
- LICENSE
- Rakefile
